module.exports = {
    es: {
        translation: {
            WELCOME_MSG: 'Bienvenido, aqui aprenderas a programar. Puedes elegir algun tema como tipos de datos. ',
            REGISTER_NAME: 'Hola {{name}} , ahora puedes tomar el curso de tipos de datos o iniciar la evaluacion. ',
            NAME: 'Nombre guardado ',
            HELP_MSG: 'Aqui aprenderas a programar. Puedes elegir algun tema como tipos de datos. ',
            GOODBYE_MSG: 'Hasta luego {{name}} !! Recuerda regresar para seguir aprendiendo',
            REFLECTOR_MSG: 'Acabas de activar {{intent}}',
            FALLBACK_MSG: 'Lo siento, no se nada sobre eso. Por favor inténtalo otra vez. ',
            ERROR_MSG: 'Lo siento, ha habido un problema. Por favor inténtalo otra vez. ',
            CANCEL_MSG: 'Vale. Aun no iniciamos el examen. ',
            SEGUIR: 'Vale, seguimos con la evaluacion',
            PEDIR_NOMBRE: ' Antes de continuar, puedes decirme tu nombre?',
            RESPUESTA_CORR: 'La respuesta es CORRECTA, tu puntuacion es:  {{cantCorrectas}} respuestas correctas de {{numPreguntas}} . Puedes pasar a la siguiente pregunta o finalizar el examen diciendo "Finalizar examen"',
            RESPUESTA_INC: 'La respuesta es INCORRECTA, tu puntuacion es: {{cantCorrectas}} respuestas correctas de {{numPreguntas}} . Puedes pasar a la siguiente pregunta o finalizar el examen diciendo "Finalizar examen"', 
            INICIA_CUEST: 'Antes, comienza el cuestionario. ',
            INICIA_CURSO: 'Antes, comienza el curso. ',
            SCORE: ' {{name}}  tu puntuacion es: {{puntuacion}} . Gracias por contestar el examen. Puedes seguir aprendiendo. ',
            SCORE_GUARDADO: ' La ultima puntuacion almacenada del examen de tipos de datos es del usuario {{nombre}} y su puntuacion fue de {{score}} . ',
            NUM_PRE: ' Pregunta {{numPregunta}} ',
            EVALUADO_CORR: 'Respuesta Correcta. ',
            EVALUADO_INC: 'Respuesta Incorrecta. ',
            PUNTUACION: ' Tu puntuacion es:  {{cantCorrectas}} respuestas correctas de {{numPreguntas}} . Puedes pasar a la siguiente pregunta o finalizar el examen diciendo "Finalizar examen"',
            QUESTION_0: '¿Cuál de los siguientes es un tipo de dato entero?, Respuestas: ',
            QUESTION_1: '¿Qué tipo de dato se utiliza para almacenar texto en programación?, Respuestas: ',
            QUESTION_2: '¿Cuál de los siguientes valores es considerado un booleano?, Respuestas: ',
            QUESTION_3: '¿Qué tipo de dato se utiliza para almacenar una colección de elementos ordenados?, Respuestas: ',
            QUESTION_4: '¿Cuál de los siguientes tipos de datos es inmutable?, Respuestas: ',
            QUESTION_5: '¿Qué tipo de dato se utiliza para almacenar pares clave-valor?, Respuestas: ',
            QUESTION_6: '¿Cuál de los siguientes no es un tipo de dato?, Respuestas: ',
            QUESTION_7: '¿Cuál de los siguientes tipos de datos solo puede tener dos posibles valores: verdadero o falso?, Respuestas: ',
            QUESTION_8: '"45", ¿Que tipo de dato es?, Respuestas: ',
            QUESTION_9: '¿Cuál de los siguientes es un tipo de dato flotante?, Respuestas: ',
            ANSWER_0: 'A) 3.14, B) "Hola", C) 42',
            ANSWER_1: 'A) Booleano, B) Cadena de texto, C) Entero',
            ANSWER_2: 'A) False, B) "Verdadero", C) 2',
            ANSWER_3: 'A) Lista , B) Diccionario, C) Entero',
            ANSWER_4: 'A) Cadena de texto, B) Diccionario, C) Tuplas',
            ANSWER_5: 'A) Cadena de texto, B) Diccionario, C) Tuplas',
            ANSWER_6: 'A) Cadena de texto, B) Variable, C) Entero',
            ANSWER_7: 'A) Booleano, B) Flotante, C) Entero',
            ANSWER_8: 'A) Booleano, B) Cadena de texto, C) Entero',
            ANSWER_9: 'A) [1, 2, 3], B) "Python", C) 3.14',
            TEMA_0: 'Bienvenido: Curso sobre tipos de datos, aqui aprenderas los tipos de datos que existen en la programacion. ',
            TEMA_1: 'Enteros: Representan números enteros sin parte decimal. Pueden ser positivos o negativos. Ejemplos: -3, 0, 42. ',
            TEMA_2: 'Flotantes: Representan números con parte decimal. También pueden ser positivos o negativos. Ejemplos: 3.14, -0.5, 1.0. ',
            TEMA_3: 'Cadenas de texto: Representan secuencias de caracteres. Se utilizan para almacenar texto. Ejemplos: "Hola", "Mundo", "¡Hola, Mundo!". ',
            TEMA_4: 'Booleanos: Representan valores lógicos. Solo pueden tener dos valores posibles, verdadero (true) o falso (false). Se utilizan para realizar operaciones de comparación y controlar el flujo de un programa. Ejemplos: true, false. ',
            TEMA_5: 'Listas: Representan una colección ordenada de elementos. Los elementos pueden ser de diferentes tipos, incluso otras listas. Se accede a los elementos mediante su posición (índice) en la lista. Ejemplo: [1, 2, 3, 4].',
            TEMA_6: 'Tuplas: Son similares a las listas, pero son inmutables, lo que significa que no se pueden modificar una vez creadas. Se utilizan para almacenar una secuencia de elementos relacionados. Ejemplo: (10, "Hola", 3.14).',
            TEMA_7: 'Diccionarios: Representan una colección de pares clave-valor. Cada elemento se almacena como una clave y su correspondiente valor. Se utilizan para buscar y almacenar datos de manera eficiente. Ejemplo: {"nombre": "Juan", "edad": 25, "ciudad": "Madrid"}.',
            TEMA_8: 'Genial, has finalizado el curso sobre tipos de datos, ahora puedes iniciar el examen. ',
            PIE_CURSO_01: 'Puedes avanzar diciendo: siguiente diapositiva',
            PIE_CURSO_02: 'Puedes decir: siguiente o anterior',
            PIE_CURSO_03: 'Puedes decir: anterior diapositiva o iniciar examen',
            PIE_CUESTIONARIO: 'Debes decir: la respuesta es A',
            TITULO:'Cuestionario sobre tipos de datos'
        }
    },
    en: {
        translation: {
            WELCOME_MSG: 'Welcome, here you will learn to program. You can choose any topic as data types. ',
            REGISTER_NAME: 'Hello {{name}} , now you can take the data types course or start the evaluation. ',
            NAME: 'saved name ',
            HELP_MSG: 'Here you will learn to program. You can choose any topic as data types. ',
            GOODBYE_MSG: 'See you later {{name}} !! Remember to come back to continue learning',
            REFLECTOR_MSG: 'You just activated {{intent}}',
            FALLBACK_MSG: 'Sorry, I dont know anything about that. Please try again. ',
            ERROR_MSG: 'Im sorry, theres been a problem. Please try again. ',
            CANCEL_MSG: 'OK. We havent started the exam yet. ',
            SEGUIR: 'Ok, lets continue with the evaluation.',
            PEDIR_NOMBRE: ' Before continuing, can you tell me your name?',
            RESPUESTA_CORR: 'The answer is CORRECT, your score is: {{cantCorrectas}} correct answers of {{numPreguntas}} . You can go to the next question or end the exam by saying "finish test"',
            RESPUESTA_INC: 'The answer is INCORRECT, your score is: {{cantCorrectas}} correct answers of {{numPreguntas}} . You can go to the next question or end the exam by saying "finish test"', 
            INICIA_CUEST: 'Before, start the quiz. ',
            INICIA_CURSO: 'Before start the course. ',
            SCORE: ' {{name}} your score is: {{puntuacion}} . Thank you for answering the test. You can keep learning. ',
            SCORE_GUARDADO: ' The last stored score of the data type exam is from user {{nombre}} and his score was {{score}} . ',
            NUM_PRE: ' Question {{numPregunta}} ',
            EVALUADO_CORR: 'Correct answer. ',
            EVALUADO_INC: 'Wrong answer. ',
            PUNTUACION: ' Your score is: {{cantCorrectas}} correct answers out of {{numPreguntas}} . You can go to the next question or end the exam by saying "End exam"',
            QUESTION_0: 'Which of the following is an integer data type?, answers: ',
            QUESTION_1: 'What data type is used to store text in programming?, answers: ',
            QUESTION_2: 'Which of the following values is considered a boolean?, answers: ',
            QUESTION_3: 'What data type is used to store an ordered collection of elements?, answers: ',
            QUESTION_4: 'Which of the following data types is immutable?, answers: ',
            QUESTION_5: 'What data type is used to store key-value pairs?, answers: ',
            QUESTION_6: 'Which of the following is not a data type?, answers: ',
            QUESTION_7: 'Which of the following data types can only have two possible values: true or false?, answers: ',
            QUESTION_8: '"45", What type of data is it?, answers: ',
            QUESTION_9: 'Which of the following is a float data type?, answers: ',
            ANSWER_0: 'A) 3.14, B) "Hello", C) 42',
            ANSWER_1: 'A) Boolean, B) String, C) Integer',
            ANSWER_2: 'A) False, B) "True", C) 2',
            ANSWER_3: 'A) List , B) Dictionary, C) Integer',
            ANSWER_4: 'A) String, B) Dictionary, C) Tuple',
            ANSWER_5: 'A) String, B) Dictionary, C) Tuple',
            ANSWER_6: 'A) String, B) Variable, C) Integer',
            ANSWER_7: 'A) Boolean, B) Floa, C) Integer',
            ANSWER_8: 'A) Boolean, B) String, C) Integer',
            ANSWER_9: 'A) [1, 2, 3], B) "Python", C) 3.14',
            TEMA_0: 'Welcome: Course on data types, here you will learn the types of data that exist in programming. ',
            TEMA_1: 'Integers: They represent whole numbers without a decimal part. They can be positive or negative. Examples: -3, 0, 42. ',
            TEMA_2: 'Floats: They represent numbers with a decimal part. They can also be positive or negative. Examples: 3.14, -0.5, 1.0. ',
            TEMA_3: 'Strings: They represent sequences of characters. They are used to store text. Examples: "Hello", "World", "Hello, World!". ',
            TEMA_4: 'Booleans: They represent logical values. They can only have two possible values, true or false. They are used for comparison operations and controlling the flow of a program. Examples: true, false. ',
            TEMA_5: 'Lists: They represent an ordered collection of elements. The elements can be of different types, including other lists. Elements are accessed by their position (index) in the list. Example: [1, 2, 3, 4]. ',
            TEMA_6: 'Tuples: They are similar to lists, but they are immutable, meaning they cannot be modified once created. They are used to store a sequence of related elements. Example: (10, "Hello", 3.14). ',
            TEMA_7: 'Dictionaries: They represent a collection of key-value pairs. Each element is stored as a key and its corresponding value. They are used for efficient data lookup and storage. Example: {"name": "John", "age": 25, "city": "Madrid"}. ',
            TEMA_8: 'Great, you´ve finished the course on data types, now you can start the exam. ',
            PIE_CURSO_01: 'You can advance by saying: next slide',
            PIE_CURSO_02: 'You can say: next or previous',
            PIE_CURSO_03: 'You can say: previous slide or start test',
            PIE_CUESTIONARIO: 'You must say: the answer is A',
            TITULO:'Data types quiz'
        }
    }
}